/**
 * SameCode: pure data and timing for the home-page widget (no DOM; `node sim.test.ts`).
 *
 * The mechanism shown follows XRobot 1.0 static assembly (docs/proj_man/gen_main.md,
 * docs/proj_man/config.md, docs/code_gen/xrobot_inter.md):
 *   - the Module BlinkLED declares the type it needs: `BlinkLED(LibXR::GPIO& led, uint32_t blink_cycle = 250)`;
 *   - the configuration User/xrobot.yaml binds that argument to a name: `- led: LED`;
 *   - each BSP's entry source constructs its own GPIO object and registers it under that name:
 *     `XR_REGISTER(LED, LibXR::GPIO);` (generated by `libxr gen --xrobot` on STM32).
 * Moving to another board changes only the entry source; the Module and the configuration stay as they are.
 */

export type BoardId = 'stm32' | 'ch32' | 'mspm0' | 'linux';

/** Code text: ⟦…⟧ marks the registered name, ⟪…⟫ marks the board-specific pin arguments. */
export type MarkedCode = string;

export type Point = [number, number];
export type Box = { x: number; y: number; w: number; h: number };

/** How LibXR's timer reaches BlinkLED on each system (src/system/timer.cpp, system/<name>/thread.cpp). */
export type Scheduling = 'thread' | 'loop';

export type Board = {
  id: BoardId;
  /** Tab title: platform; `system` is translated in the widget. */
  platform: string;
  system: 'threadx' | 'freertos' | 'none' | 'linux';
  /** LIBXR_SYSTEM value used by the platform's CMake. */
  libxrSystem: string;
  /**
   * thread: Timer::Add creates the thread libxr_timer_task, which calls Timer::Refresh and then
   * Thread::SleepUntil(time, 1) (ThreadX / FreeRTOS tick, Linux clock_nanosleep).
   * loop: system/none has no threads; Thread::Sleep / SleepUntil spin on the 1 ms time base and call
   * Timer::RefreshTimerInIdle, which runs Timer::Refresh once per elapsed millisecond.
   */
  scheduling: Scheduling;
  entryFile: string;
  /** True when the entry source is written by the CodeGenerator (`libxr gen --xrobot`). */
  generated: boolean;
  entry: MarkedCode;
  /** Pin that drives the LED, as printed on the board's silkscreen. */
  pin: string;
  /** Drawing: static/showcase/samecode/<id>.svg; anchors in ./art.ts. */
  art: string;
};

export const REGISTERED_NAME = 'LED';
export const BLINK_CYCLE_MS = 250;
/** Board stage viewBox (0 0 STAGE_W STAGE_H); the drawing is fitted into BOARD_RECT, the name tag sits at TAG. */
export const STAGE_W = 360;
export const STAGE_H = 200;
export const BOARD_RECT: Box = { x: 0, y: 24, w: 360, h: 176 };
export const TAG: Box = { x: 314, y: 4, w: 44, h: 20 };
/** Horizontal run of the binding line from the pin up to the tag. */
export const BINDING_Y = TAG.y + TAG.h / 2;

export const MODULE_FILE = 'Modules/xrobot-org/BlinkLED/BlinkLED.hpp';
export const MODULE_CODE: MarkedCode = 'BlinkLED(LibXR::GPIO& led, uint32_t blink_cycle = 250);';

export const CONFIG_FILE = 'User/xrobot.yaml';
export const CONFIG_CODE: MarkedCode = '- module: xrobot-org/BlinkLED\n  id: blinkled_0\n  args:\n    - led: ⟦LED⟧\n    - blink_cycle: 250';

export const BOARDS: Board[] = [
  {
    id: 'stm32',
    pin: 'PC13',
    scheduling: 'thread',
    art: '/showcase/samecode/stm32.svg',
    platform: 'STM32',
    system: 'threadx',
    libxrSystem: 'ThreadX',
    entryFile: 'User/app_main.cpp',
    generated: true,
    entry: 'static STM32GPIO ⟦LED⟧(⟪LED_GPIO_Port, LED_Pin⟫);\n// ...\nXR_REGISTER(⟦LED⟧, LibXR::GPIO);',
  },
  {
    id: 'ch32',
    pin: 'PA15',
    scheduling: 'thread',
    art: '/showcase/samecode/ch32.svg',
    platform: 'CH32',
    system: 'freertos',
    libxrSystem: 'FreeRTOS',
    entryFile: 'User/app_main.cpp',
    generated: false,
    entry: 'static LibXR::CH32GPIO ⟦LED⟧(⟪GPIOA, GPIO_Pin_15⟫);\n// ...\nXR_REGISTER(⟦LED⟧, LibXR::GPIO);',
  },
  {
    id: 'mspm0',
    pin: 'PB22',
    scheduling: 'loop',
    art: '/showcase/samecode/mspm0.svg',
    platform: 'MSPM0',
    system: 'none',
    libxrSystem: 'None',
    entryFile: 'User/app_main.cpp',
    generated: false,
    entry: 'static LibXR::MSPM0GPIO ⟦LED⟧(⟪GPIOB, DL_GPIO_PIN_22, IOMUX_PINCM50⟫);\n// ...\nXR_REGISTER(⟦LED⟧, LibXR::GPIO);',
  },
  {
    id: 'linux',
    pin: 'GPIO17',
    scheduling: 'thread',
    art: '/showcase/samecode/linux.svg',
    platform: 'Linux',
    system: 'linux',
    libxrSystem: 'Linux',
    entryFile: 'User/main.cpp',
    generated: false,
    entry: 'static LibXR::LinuxGPIO ⟦LED⟧(⟪"/dev/gpiochip0", 17⟫);\n// ...\nXR_REGISTER(⟦LED⟧, LibXR::GPIO);',
  },
];

/** BlinkLED toggles the LED every `cycle` ms; the first toggle (to on) happens at t = cycle. */
export function ledLevel(tMs: number, cycle: number = BLINK_CYCLE_MS): boolean {
  if (tMs < 0) return false;
  return Math.floor(tMs / cycle) % 2 === 1;
}

/**
 * Logic-analyzer trace of the last `windowMs` before `tMs`, in viewBox units where x is time in
 * ms (0 … windowMs) and y is `high` or `low`. Returns an SVG `points` string.
 */
export function tracePoints(tMs: number, windowMs: number, high: number, low: number, cycle: number = BLINK_CYCLE_MS): string {
  const start = tMs - windowMs;
  const y = (t: number) => (ledLevel(t, cycle) ? high : low);
  const pts: string[] = [`0,${y(start)}`];
  let edge = (Math.floor(start / cycle) + 1) * cycle;
  while (edge < tMs) {
    const x = edge - start;
    pts.push(`${x},${y(edge - 1e-6)}`, `${x},${y(edge)}`);
    edge += cycle;
  }
  pts.push(`${windowMs},${y(tMs)}`);
  return pts.join(' ');
}

/** Splits marked code into plain text and marked runs. */
export type CodeRun = { text: string; mark?: 'name' | 'pin' };
export function splitMarks(code: MarkedCode): CodeRun[] {
  const runs: CodeRun[] = [];
  const re = /⟦([^⟧]*)⟧|⟪([^⟫]*)⟫/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(code)) !== null) {
    if (m.index > last) runs.push({ text: code.slice(last, m.index) });
    if (m[1] !== undefined) runs.push({ text: m[1], mark: 'name' });
    else runs.push({ text: m[2], mark: 'pin' });
    last = m.index + m[0].length;
  }
  if (last < code.length) runs.push({ text: code.slice(last) });
  return runs;
}

/** Plain text of marked code. */
export function plainText(code: MarkedCode): string {
  return splitMarks(code)
    .map((run) => run.text)
    .join('');
}

/** Fits a drawing (viewBox) into `rect`, centred, keeping its aspect; returns the placement and a point mapper. */
export function fit(viewBox: [number, number, number, number], rect: Box): Box & { map: (p: Point) => Point } {
  const [vx, vy, vw, vh] = viewBox;
  const s = Math.min(rect.w / vw, rect.h / vh);
  const w = vw * s;
  const h = vh * s;
  const x = rect.x + (rect.w - w) / 2;
  const y = rect.y + (rect.h - h) / 2;
  return { x, y, w, h, map: ([px, py]) => [x + (px - vx) * s, y + (py - vy) * s] };
}

/** Binding line: from the pin straight up to the tag's row, then right to the tag. */
export function bindingPoints(pin: Point): Point[] {
  return [pin, [pin[0], BINDING_Y], [TAG.x, BINDING_Y]];
}

/**
 * Scheduling lane over the same window as the LED trace (x = ms, 0 … windowMs): `wakes` are the timer
 * refreshes drawn every `wakeStepMs` (the 1 ms refreshes, thinned so they stay visible), `runs` are the
 * refreshes that reach the 250 ms count and call BlinkLED (the LED edges). Returns an SVG path `d`.
 */
export function laneTicks(tMs: number, windowMs: number, wakeStepMs: number, low: number, wakeTop: number, runTop: number, cycle: number = BLINK_CYCLE_MS): string {
  const start = tMs - windowMs;
  const out: string[] = [];
  for (let e = Math.ceil(start / wakeStepMs) * wakeStepMs; e <= tMs; e += wakeStepMs) {
    const x = +(e - start).toFixed(1);
    const top = e % cycle === 0 ? runTop : wakeTop;
    out.push(`M${x} ${low}V${top}`);
  }
  return out.join('');
}

export function nextBoard(id: BoardId, step = 1): BoardId {
  const i = BOARDS.findIndex((b) => b.id === id);
  return BOARDS[(i + step + BOARDS.length) % BOARDS.length].id;
}
